<?php

require_once 'D:\xampp\htdocs\ezp\extension\eztotp\operators\EzTotpUserOperator.php';

/**
 * Test class for EzTotpUserOperator.
 * Generated by PHPUnit on 2012-04-03 at 21:43:58.
 */
class EzTotpUserOperatorTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var EzTotpUserOperator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new EzTotpUserOperator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers EzTotpUserOperator::operatorList
     */
    public function testOperatorList()
    {
        $this->assertGreaterThan(1, count($this->object->operatorList()));
    }

}
?>
