<?php
/**
 * EzTotp: Two-factor authentication with Google Authenticator for eZPublish
 *
 * @package EzTotp
 * @version 0.2
 * @author Frank Neff <fneff89@gmail.com>
 * @license LGPL v3 - http://www.gnu.org/licenses/lgpl-3.0.en.html
 */
/**
 * Test class for EzTotpUserPersistentObject.
 * Generated by PHPUnit on 2012-04-03 at 21:40:45.
 */
class EzTotpUserPersistentObjectTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var EzTotpUserPersistentObject
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new EzTotpUserPersistentObject;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers EzTotpUserPersistentObject::definition
     */
    public function testDefinition()
    {
        $this->assertTrue(is_array(EzTotpUserPersistentObject::definition()));
    }
}
?>
