<?php

require_once 'D:\xampp\htdocs\ezp\extension\eztotp\classes\components\EzTotpUser.php';

/**
 * Test class for EzTotpUser.
 * Generated by PHPUnit on 2012-04-03 at 21:36:43.
 */
class EzTotpUserTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var EzTotpUser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers EzTotpUser::definition
     */
    public function testDefinition()
    {
        // Remove the following lines when you implement this test.
        $this->assertArrayHasKey("class_name", EzTotpUser::definition());
    }
}
?>
