<?php

/**
 * Test class for EzTotpConfiguration.
 * Generated by PHPUnit on 2012-04-03 at 19:48:42.
 */
class EzTotpConfigurationTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var EzTotpConfiguration
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new EzTotpConfiguration;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers EzTotpConfiguration::USER_STATE_OTP
     * @covers EzTotpConfiguration::USER_STATE_NOOTP
     * @covers EzTotpConfiguration::USER_STATE_BLOCKED
     */
    public function testConstants()
    {
        $staticClassName = get_class($this->object);
        $this->assertTrue(is_int($staticClassName::USER_STATE_OTP));
        $this->assertTrue(is_int($staticClassName::USER_STATE_NOOTP));
        $this->assertTrue(is_int($staticClassName::USER_STATE_BLOCKED));
    }

    public function testLoadConfiguration()
    {
        $this->object->loadConfiguration();
    }
}
?>
