<?php

/**
 * Test class for EzTotpConfiguration.
 * Generated by PHPUnit on 2012-04-03 at 19:48:42.
 */
class EzTotpConfigurationTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var EzTotpConfiguration
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new EzTotpConfiguration;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }


    public function testConstants()
    {
        $staticClassName = get_class($this->object);
        $this->assertTrue(is_int($staticClassName::USER_STATE_OTP));
        $this->assertTrue(is_int($staticClassName::USER_STATE_NOOTP));
        $this->assertTrue(is_int($staticClassName::USER_STATE_BLOCKED));
    }

    public function testLoadConfiguration()
    {
        $this->object->loadConfiguration();
    }

    public function testConfigurationArray()
    {
        $ini = eZINI::instance("eztotp.ini", __DIR__ . "../../settings/");

        var_dump($ini);


        $this->object->loadConfiguration();
        $config = $this->object->getData();
        $this->assertTrue(is_array($config));
        $this->assertTrue(count($config) > 0);
    }
}
?>
