<?php
/**
 * EzTotp: Two-factor authentication with Google Authenticator for eZPublish
 *
 * @package EzTotp
 * @version 0.3
 * @author Frank Neff <frankneff.ch>
 * @license LGPL v3 - http://www.gnu.org/licenses/lgpl-3.0.en.html
 */

/**
 * Test class for EzTotpAuthenticationHelperAbstract.
 * Generated by PHPUnit on 2012-04-03 at 20:57:13.
 */
class EzTotpAuthenticationHelperAbstractTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var EzTotpAuthenticationHelperAbstract
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $ini = new eZINI("eztotp.ini", 'extension/eztotp/settings', null, null, true);
        $ini->resetOverrideDirs();
        $ini->resetGlobalOverrideDirs();
        $ini->load(true);

        $config = new EzTotpConfiguration();
        $config->loadConfiguration($ini);
        $this->object = new EzTotpAuthentication($config);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers EzTotpAuthenticationHelperAbstract::generate_secret_key
     */
    public function testGenerate_secret_key()
    {
        $this->assertEquals(30, strlen($this->object->generate_secret_key(30)));
    }
}

?>
